#!/usr/bin/env python3
"""Global Sentinel V4 — Flash Memo Generator

Produces executive-ready flash memos when regime conditions warrant.
Separates observed facts from inferences. Cites data freshness and confidence.
"""

import json
from datetime import datetime, timezone
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


class FlashMemoGenerator:
    """Generate flash memos from monitoring cycle outputs."""

    def generate(self, cycle_output: dict) -> str:
        """Generate a flash memo markdown file from cycle output."""
        ts = cycle_output["timestamp_utc"]
        mode = cycle_output["mode"]
        regime_p = cycle_output.get("regime_shift_probability", 0)
        confidence = cycle_output.get("confidence", 0)
        components = cycle_output.get("component_scores", {})
        evidence = cycle_output.get("evidence", [])
        freshness = cycle_output.get("data_freshness_status", {})
        veto = cycle_output.get("manual_veto_status", False)
        kill = cycle_output.get("kill_switch_status", False)
        fallback = cycle_output.get("fallback_mode_status", False)
        shadow = cycle_output.get("shadow_execution_eligible", False)

        memo_lines = [
            f"# Flash Memo — {ts}",
            "",
            f"**Mode:** {mode}  ",
            f"**Regime Shift Probability:** {regime_p:.3f}  ",
            f"**Confidence:** {confidence:.2f}  ",
            f"**Fallback Mode:** {'YES' if fallback else 'No'}  ",
            f"**Shadow Draft Eligible:** {'YES' if shadow else 'No'}  ",
            f"**Manual Veto:** {'ACTIVE' if veto else 'Inactive'}  ",
            f"**Kill Switch:** {'ACTIVE' if kill else 'Inactive'}  ",
            "",
            "## Component Scores",
            "",
        ]

        for k, v in sorted(components.items()):
            fresh = freshness.get(k, "unknown")
            memo_lines.append(f"- **{k}:** {v:.3f} (fresh: {fresh})")

        memo_lines.extend([
            "",
            "## Observed Facts (from data sources)",
            "",
        ])
        for e in evidence:
            memo_lines.append(f"- {e}")
        if not evidence:
            memo_lines.append("- No specific evidence items this cycle.")

        memo_lines.extend([
            "",
            "## Inferences",
            "",
            f"- Composite regime probability of {regime_p:.3f} suggests "
            f"{'heightened' if regime_p > 0.5 else 'moderate' if regime_p > 0.3 else 'low'} "
            f"geopolitical stress.",
            f"- Confidence of {confidence:.2f} "
            f"{'is below minimum for shadow drafts' if confidence < 0.5 else 'supports shadow analysis'}.",
            "",
            "## Data Gaps / Uncertainty",
            "",
        ])

        stale = [k for k, v in freshness.items() if not v]
        if stale:
            memo_lines.append(f"- Stale sources: {', '.join(stale)}")
        if fallback:
            memo_lines.append("- Operating in FALLBACK mode — reduced data quality.")
        if not stale and not fallback:
            memo_lines.append("- All data sources fresh.")

        memo_lines.extend([
            "",
            "---",
            f"*Generated by Global Sentinel V4 at {ts}*",
        ])

        memo_text = "\n".join(memo_lines)

        # Write to reports/flash/
        safe_ts = ts.replace(":", "-")
        memo_path = PROJECT_ROOT / "reports" / "flash" / f"flash-{safe_ts}.md"
        memo_path.write_text(memo_text)

        return str(memo_path)
