"""Replay engine for backtesting pipeline versions against point-in-time data."""
from __future__ import annotations

import gzip
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Callable

logger = logging.getLogger(__name__)


class ReplayEngine:
    """Replays point-in-time snapshots through analysis pipelines for backtesting."""

    def __init__(self, repo_root: str | Path | None = None) -> None:
        if repo_root is None:
            repo_root = Path(__file__).resolve().parents[2]
        self.repo_root = Path(repo_root)
        self.reports_dir = self.repo_root / "reports" / "operational"

    # ── Core replay ──────────────────────────────────────────────────

    def replay(
        self,
        snapshots: list[dict[str, Any]],
        pipeline_fn: Callable[[dict[str, Any]], dict[str, Any]] | None = None,
    ) -> list[dict[str, Any]]:
        """Replay PIT snapshots through a pipeline function.

        Takes snapshots from PointInTimeDataStore and feeds each through
        pipeline_fn (or a default pass-through analysis).

        Returns a list of results, each containing:
        - snapshot_date: the date of the snapshot
        - trade_ideas: ideas generated by the pipeline
        - signals_fired: signals that triggered
        - edge_detected: any detected statistical edge
        """
        if pipeline_fn is None:
            pipeline_fn = self._default_pipeline

        results: list[dict[str, Any]] = []
        for i, snapshot in enumerate(snapshots):
            snap_date = snapshot.get("date", snapshot.get("timestamp", f"snap_{i}"))
            logger.info("Replaying snapshot %s (%d/%d)", snap_date, i + 1, len(snapshots))

            try:
                output = pipeline_fn(snapshot)
            except Exception as exc:
                logger.error("Pipeline failed on snapshot %s: %s", snap_date, exc)
                output = {"error": str(exc)}

            results.append({
                "snapshot_date": snap_date,
                "trade_ideas": output.get("trade_ideas", []),
                "signals_fired": output.get("signals_fired", []),
                "edge_detected": output.get("edge_detected", {}),
                "raw_output": output,
            })

        logger.info("Replay complete: %d snapshots processed", len(results))
        return results

    # ── Backtesting ──────────────────────────────────────────────────

    def backtest(
        self,
        start_date: str | None = None,
        end_date: str | None = None,
        strategies: list[str] | None = None,
    ) -> dict[str, Any]:
        """Run a backtest over a date range with optional strategy filter.

        Returns:
            total_pnl: estimated PnL if all ideas had been executed
            per_strategy: breakdown by strategy name
            signal_accuracy: fraction of signals that preceded moves
            false_signals: count of signals that didn't lead to moves
            missed_opportunities: moves that occurred without prior signals
        """
        start = start_date or "1970-01-01"
        end = end_date or datetime.now(timezone.utc).strftime("%Y-%m-%d")

        logger.info(
            "Backtesting %s to %s, strategies=%s",
            start, end, strategies or "all",
        )

        # Load replay results from reports if available
        replay_files = self._find_replay_reports(start, end)
        all_ideas: list[dict[str, Any]] = []
        all_signals: list[dict[str, Any]] = []

        for report_path in replay_files:
            report = self._load_report(report_path)
            if report is None:
                continue
            for entry in report.get("results", []):
                all_ideas.extend(entry.get("trade_ideas", []))
                all_signals.extend(entry.get("signals_fired", []))

        # Filter by strategy if specified
        if strategies:
            strategy_set = {s.lower() for s in strategies}
            all_ideas = [
                idea for idea in all_ideas
                if idea.get("strategy", "").lower() in strategy_set
            ]

        # Compute backtest metrics
        total_pnl = sum(float(idea.get("estimated_pnl", 0)) for idea in all_ideas)
        per_strategy: dict[str, float] = {}
        for idea in all_ideas:
            strat = idea.get("strategy", "unknown")
            per_strategy[strat] = per_strategy.get(strat, 0.0) + float(
                idea.get("estimated_pnl", 0)
            )

        accurate_signals = sum(
            1 for s in all_signals if s.get("followed_by_move", False)
        )
        total_signals = len(all_signals)
        false_signals = sum(
            1 for s in all_signals if not s.get("followed_by_move", False)
        )
        missed = sum(
            1 for s in all_signals if s.get("missed_opportunity", False)
        )

        return {
            "start_date": start,
            "end_date": end,
            "total_pnl": round(total_pnl, 2),
            "per_strategy": {k: round(v, 2) for k, v in per_strategy.items()},
            "signal_accuracy": (
                round(accurate_signals / total_signals, 4) if total_signals else 0.0
            ),
            "false_signals": false_signals,
            "missed_opportunities": missed,
            "total_ideas": len(all_ideas),
            "total_signals": total_signals,
        }

    # ── Version comparison ───────────────────────────────────────────

    def compare_versions(
        self,
        snapshots: list[dict[str, Any]],
        pipeline_v1: Callable[[dict[str, Any]], dict[str, Any]],
        pipeline_v2: Callable[[dict[str, Any]], dict[str, Any]],
    ) -> dict[str, Any]:
        """Compare two pipeline versions on the same snapshots.

        Returns v1_results, v2_results, improvement_pct, and a summary.
        """
        logger.info("Comparing pipeline versions on %d snapshots", len(snapshots))

        v1_results = self.replay(snapshots, pipeline_fn=pipeline_v1)
        v2_results = self.replay(snapshots, pipeline_fn=pipeline_v2)

        v1_pnl = sum(
            sum(float(idea.get("estimated_pnl", 0)) for idea in r.get("trade_ideas", []))
            for r in v1_results
        )
        v2_pnl = sum(
            sum(float(idea.get("estimated_pnl", 0)) for idea in r.get("trade_ideas", []))
            for r in v2_results
        )

        improvement_pct = (
            round(((v2_pnl - v1_pnl) / abs(v1_pnl)) * 100, 2)
            if v1_pnl != 0
            else 0.0
        )

        return {
            "v1_results": v1_results,
            "v2_results": v2_results,
            "v1_pnl": round(v1_pnl, 2),
            "v2_pnl": round(v2_pnl, 2),
            "improvement_pct": improvement_pct,
            "summary": (
                f"V2 would have made ${v2_pnl:,.2f} vs V1 ${v1_pnl:,.2f} "
                f"({improvement_pct:+.1f}%)"
            ),
        }

    # ── Reporting ────────────────────────────────────────────────────

    def generate_report(
        self,
        backtest_results: dict[str, Any],
        date: str | None = None,
    ) -> Path:
        """Save backtest results to reports/operational/replay_{date}.json."""
        if date is None:
            date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

        self.reports_dir.mkdir(parents=True, exist_ok=True)
        report_path = self.reports_dir / f"replay_{date}.json"

        report = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "date": date,
            "results": backtest_results,
        }

        with open(report_path, "w") as fh:
            json.dump(report, fh, indent=2, default=str)

        logger.info("Replay report saved to %s", report_path)
        return report_path

    def format_telegram(self) -> str:
        """Format latest replay comparison for Telegram digest."""
        # Find the most recent replay report
        if not self.reports_dir.exists():
            return "\U0001f504 Replay: No reports available"

        reports = sorted(self.reports_dir.glob("replay_*.json"), reverse=True)
        if not reports:
            return "\U0001f504 Replay: No reports available"

        try:
            with open(reports[0], "r") as fh:
                report = json.load(fh)
        except (json.JSONDecodeError, OSError):
            return "\U0001f504 Replay: Error reading latest report"

        results = report.get("results", {})

        # Check if this is a comparison report
        if "v1_pnl" in results and "v2_pnl" in results:
            v1 = results["v1_pnl"]
            v2 = results["v2_pnl"]
            pct = results.get("improvement_pct", 0)
            date_range = results.get("start_date", "?")
            end_range = results.get("end_date", "?")
            return (
                f"\U0001f504 Replay: V2 would have made ${v2:,.0f} vs "
                f"V1 ${v1:,.0f} on {date_range}-{end_range} ({pct:+.0f}%)"
            )

        # Standard backtest report
        total_pnl = results.get("total_pnl", 0)
        accuracy = results.get("signal_accuracy", 0)
        ideas = results.get("total_ideas", 0)
        return (
            f"\U0001f504 Replay: ${total_pnl:,.0f} est. PnL, "
            f"{accuracy:.0%} signal accuracy, {ideas} ideas"
        )

    # ── Internal helpers ─────────────────────────────────────────────

    @staticmethod
    def _default_pipeline(snapshot: dict[str, Any]) -> dict[str, Any]:
        """Default pass-through pipeline that returns the snapshot as-is."""
        return {
            "trade_ideas": snapshot.get("trade_ideas", []),
            "signals_fired": snapshot.get("signals_fired", []),
            "edge_detected": snapshot.get("edge_detected", {}),
        }

    def _find_replay_reports(self, start: str, end: str) -> list[Path]:
        """Find replay report files within a date range."""
        if not self.reports_dir.exists():
            return []
        reports: list[Path] = []
        for path in sorted(self.reports_dir.glob("replay_*.json")):
            # Extract date from filename: replay_YYYY-MM-DD.json
            stem = path.stem  # replay_2026-03-08
            date_part = stem.replace("replay_", "")
            if start <= date_part <= end:
                reports.append(path)
        return reports

    @staticmethod
    def _load_report(path: Path) -> dict[str, Any] | None:
        """Load a replay report from JSON (plain or gzipped)."""
        try:
            if path.suffix == ".gz":
                with gzip.open(path, "rt") as fh:
                    return json.load(fh)
            else:
                with open(path, "r") as fh:
                    return json.load(fh)
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning("Failed to load report %s: %s", path, exc)
            return None
